use crate::fault::{FaultCode, FaultDetail, RawFaultDetail};
use core::fmt;

/// Decomposed view of a [`Fault`].
///
/// The default [`RawFaultDetail`] form stays compact for hot paths. Typed
/// detail enums generated by `define_fault_details!` are intended for logs,
/// reports, and boundary rendering after decoding with [`Fault::parts_as`].
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub struct FaultParts<D = RawFaultDetail> {
	/// Stable fault domain.
	pub domain: u16,
	/// Domain-local fault code.
	pub code: u16,
	/// Cheap caller-defined detail.
	pub detail: D,
}

/// Fixed 8-byte fault object for hot paths.
///
/// Layout:
///
/// ```text
/// [ domain:16 ][ code:16 ][ detail:32 ]
/// ```
///
/// `detail` is stored as a compact id. Callers should prefer typed detail
/// enums generated by `define_fault_details!` over passing raw numbers.
#[repr(transparent)]
#[derive(Copy, Clone, Default, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Fault(u64);

impl Fault {
	/// Success sentinel. Normal success should still use `Ok(T)`.
	pub const OK: Self = Self::new(0, 0, 0);

	/// Creates a fault from raw stable fields.
	///
	/// This constructor is intended for low-level decoding, tests, and raw
	/// bridges. Normal code should prefer [`Fault::from_code`] or
	/// [`FaultCode::fault_with`] with a typed detail enum generated by
	/// `define_fault_details!`.
	#[inline(always)]
	pub const fn new(domain: u16, code: u16, detail: u32) -> Self {
		Self(((domain as u64) << 48) | ((code as u64) << 32) | detail as u64)
	}

	/// Creates a fault from raw stable fields.
	///
	/// Prefer typed constructors such as [`Fault::from_code`] when the detail
	/// has domain meaning.
	#[inline(always)]
	pub const fn from_raw_parts(domain: u16, code: u16, detail: u32) -> Self {
		Self::new(domain, code, detail)
	}

	/// Creates a fault from a typed code and typed detail.
	#[inline(always)]
	pub fn from_code<C, D>(code: C, detail: D) -> Self
	where
		C: FaultCode,
		D: FaultDetail,
	{
		Self::from_code_raw(code, detail.id())
	}

	/// Creates a fault from a typed code and raw detail id.
	///
	/// Use this for deserialization, FFI, migration, or bottom-level system
	/// codes. Normal code should pass a typed [`FaultDetail`] instead.
	#[inline(always)]
	pub fn from_code_raw<C>(code: C, detail: u32) -> Self
	where
		C: FaultCode,
	{
		Self::new(code.domain(), code.code(), detail)
	}

	/// Creates a fault from a typed code with zero detail.
	#[inline(always)]
	pub fn code<C>(code: C) -> Self
	where
		C: FaultCode,
	{
		Self::from_code_raw(code, 0)
	}

	/// Rebuilds a fault from the encoded 64-bit representation.
	#[inline(always)]
	pub const fn from_raw(raw: u64) -> Self {
		Self(raw)
	}

	/// Returns the encoded 64-bit representation.
	#[inline(always)]
	pub const fn raw(self) -> u64 {
		self.0
	}

	/// Returns the stable fault domain.
	#[inline(always)]
	pub const fn domain(self) -> u16 {
		(self.0 >> 48) as u16
	}

	/// Returns the domain-local fault code.
	#[inline(always)]
	pub const fn code_id(self) -> u16 {
		((self.0 >> 32) & 0xffff) as u16
	}

	/// Returns the caller-defined detail.
	#[inline(always)]
	pub const fn detail(self) -> u32 {
		(self.0 & 0xffff_ffff) as u32
	}

	/// Returns the raw caller-defined detail id.
	#[inline(always)]
	pub const fn detail_raw(self) -> u32 {
		self.detail()
	}

	/// Returns the decomposed stable fields.
	#[inline(always)]
	pub const fn parts(self) -> FaultParts<RawFaultDetail> {
		FaultParts {
			domain: self.domain(),
			code: self.code_id(),
			detail: RawFaultDetail::new(self.detail_raw()),
		}
	}

	/// Returns the decomposed stable fields with a typed detail enum.
	#[inline(always)]
	pub fn parts_as<D>(self) -> FaultParts<D>
	where
		D: FaultDetail,
	{
		FaultParts {
			domain: self.domain(),
			code: self.code_id(),
			detail: D::from_id(self.detail_raw()),
		}
	}

	/// Returns the same domain/code with a different typed detail.
	#[inline(always)]
	pub fn with_detail<D>(self, detail: D) -> Self
	where
		D: FaultDetail,
	{
		self.with_detail_raw(detail.id())
	}

	/// Returns the same domain/code with a different raw detail id.
	#[inline(always)]
	pub const fn with_detail_raw(self, detail: u32) -> Self {
		Self::new(self.domain(), self.code_id(), detail)
	}

	/// Returns whether this value is the success sentinel.
	#[inline(always)]
	pub const fn is_ok(self) -> bool {
		self.0 == Self::OK.0
	}
}

impl fmt::Debug for Fault {
	fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
		f.debug_struct("Fault")
			.field("domain", &self.domain())
			.field("code", &self.code_id())
			.field("detail", &self.detail())
			.field("raw", &self.raw())
			.finish()
	}
}

impl fmt::Display for Fault {
	fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
		write!(
			f,
			"fault domain={} code={} detail={} raw={}",
			self.domain(),
			self.code_id(),
			self.detail(),
			self.raw()
		)
	}
}

impl std::error::Error for Fault {}

#[cfg(test)]
mod tests {
	use super::{Fault, FaultParts};
	use crate::fault::{FaultCode, FaultDetail, FaultReport, FaultResult, InfraDetail, InfraFault, RawFaultDetail};
	use core::mem::size_of;

	#[test]
	fn fault_is_8_bytes() {
		assert_eq!(size_of::<Fault>(), 8);
	}

	#[test]
	fn fault_parts_is_8_bytes() {
		assert_eq!(size_of::<FaultParts>(), 8);
		assert_eq!(size_of::<FaultParts<RawFaultDetail>>(), 8);
	}

	#[test]
	fn typed_fault_parts_is_boundary_view() {
		assert_eq!(size_of::<InfraDetail>(), 8);
		assert_eq!(size_of::<FaultParts<InfraDetail>>(), 12);
	}

	#[test]
	fn fault_result_error_formats_report_message() {
		let result: FaultResult<()> = Err(FaultReport::from(
			InfraFault::ConfigLoad.fault_with(InfraDetail::ConfigPath),
		));
		let err = result.unwrap_err();

		assert_eq!(err.to_string(), "Configuration load failed");
		assert_eq!(format!("{err:?}"), "Configuration load failed");
	}

	#[test]
	fn fault_round_trips_parts() {
		let fault = Fault::new(7, 2001, 42);

		assert_eq!(fault.domain(), 7);
		assert_eq!(fault.code_id(), 2001);
		assert_eq!(fault.detail(), 42);
		assert_eq!(fault.detail_raw(), 42);
		assert_eq!(Fault::from_raw(fault.raw()), fault);
	}

	#[test]
	fn fault_parts_decode_raw_detail_by_default() {
		let parts = Fault::new(7, 2001, 42).parts();

		assert_eq!(parts.domain, 7);
		assert_eq!(parts.code, 2001);
		assert_eq!(parts.detail.id(), 42);
		assert_eq!(parts.detail.detail(), "raw detail id");
	}

	#[test]
	fn fault_parts_decode_typed_detail() {
		let parts = Fault::new(1, 1002, 1).parts_as::<InfraDetail>();

		assert_eq!(parts.detail, InfraDetail::ConfigPath);
		assert_eq!(parts.detail.detail(), "config file path");
	}
}
